root = "."
tmp_dir = ".air"

[build]
  bin = "./.air/bytebase"
  cmd = "go build -o ./.air/bytebase ./cmd/server/"
  delay = 1000
  exclude_dir = [".air", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""